version: '3.8'

services:
  web:
    env_file:
      - .env
    build: .
    image: immacora/oclettings:1.0.0
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    container_name: oclettings_django_web_app