# Generated by Django 4.2.6 on 2023-10-14 05:17

from django.db import migrations


def delete_oc_lettings_site_entries(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='oc_lettings_site').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RunPython(delete_oc_lettings_site_entries),
        migrations.DeleteModel(name='Address'),
        migrations.DeleteModel(name='Letting'),
        migrations.DeleteModel(name='Profile'),
    ]
